# Name for the workflow
name: Continuous integration

# Select when the actions will be triggered
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  repository_dispatch:

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
    - name: "Accessing the GitHub repository"
      uses: actions/checkout@v2

    - name: "Installing dependencies"
      run: |
        sudo apt-get update
        sudo apt-get install build-essential ghostscript asymptote

    - name: "Installing LaTeX"
      run: |
        sudo apt-get install texlive-full

    - name: "Setting up Python 3.8"
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: "Installing cookiecutter"
      run: |
        python -m pip install --upgrade pip
        python -m pip install cookiecutter

    - name: "Creating a new ESCRIBA project"
      run: |
        cookiecutter --no-input .

    - name: "Render ESCRIBA project"
      run: |
        cd escriba_project && make pdf
